left_arm:
  type: eyou
  ids:
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  length_per_radian:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  invert_directions:
  - false
  - true
  - false
  - true
  - false
  - true
  - false
  control_freq: 250
  interpolation_points: 13
  max_velocity: 0.4
  gravity_compensation_tolerance: 0.0
  friction_compensation_scale: 0.0
  friction_compensation_stiffness: 10
  external_protections: []
  protection_rebound: 0.0
  offset_at_hardware_zero:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  joint_names:
  - left-joint_arm_1
  - left-joint_arm_2
  - left-joint_arm_3
  - left-joint_arm_4
  - left-joint_arm_5
  - left-joint_arm_6
  - left-joint_arm_7
  max_torque:
  - 1800
  - 1800
  - 2400
  - 2400
  - 2000
  - 2000
  - 2000
  admittance_config:
    param_mass:
    - 1.8
    - 1.8
    - 1.8
    - 0.03
    - 0.03
    - 0.03
    param_stiff:
    - 180.0
    - 180.0
    - 180.0
    - 3.0
    - 3.0
    - 3.0
    param_damp:
    - 18.0
    - 18.0
    - 18.0
    - 0.3
    - 0.3
    - 0.3
    param_wrench_zero:
    - 2.5779239092422594
    - 42.02327667074542
    - -19.39662434996873
    - 0.23820470224030293
    - 0.2043194390805617
    - 2.907777189236797
    param_gravity:
    - 0.10514866833203614
    - -0.33545558893262495
    - -7.6291726010996594
    param_mass_pos:
    - 0.0021563534188932957
    - -0.0002791071588437166
    - 0.0615232243609378
    deadband: 10.0
    lock_rotate: false
    freeze_step: 37
  force_sensor_name: left_force_sensor
  expected_urdf_link_name: left-link_ee_ft_sensor
  waist_angle: 0.0
